### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by kashyap32** [llSourcell/how_to_deploy_a_keras_model_to_production#1]
when I tried to predict the image I am getting this error , TypeError: a bytes-like object is required, not 'str'
what should I do?

**Comment by khangprolxag** [comment]
I'm using python 3 and then got this error

**Comment by frankherfert** [comment]
Python 3 doesn't handle base64 encoding (which is a pure ASCII encoding) the same way as Python 2.

You can use this function instead:

```
import base64

def convertImage(imgData1):
    imgstr = re.search(b'data:image/png;base64,(.*)', imgData1).group(1)
    with open('output.png', 'wb') as output:
        output.write(base64.b64decode(imgstr))
```

If you pass the image to Python through the "Predict" button, something like this gets returned:
`b'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARgAAAEYCAYAAACHjumMAAAdlklEQVR4Xu2de2jX1RvHH295XWppKAbOFDQvqJFibEwNpgZBin+UWOiwkChzpqKx2VxqKrm8VGSgTUElQ0ihUFfkbSPUnIrWjLxGorHBnNeVU388Xz`

With the regex, you remove the part before the actual image data.

You also need to change the paths in the load.py file if you place your models in a "model" folder.

**Comment by khangprolxag** [comment]
wow! I know the first part of base64 string . but I don't know how to remove it.
Amazing, now I can fix it ✌️ thank you

**Comment by kashyap32** [comment]
OK, Thanks @frankherfert . Problem solved.

**Comment by HemantBelwal** [comment]
Traceback (most recent call last):
  File "netconf_tool.py", line 18, in <module>
    tn.read_until("login: ")
  File "C:\lib\telnetlib.py", line 302, in read_until
    i = self.cookedq.find(match)
TypeError: a bytes-like object is required, not 'str'


Code snippet:
!/usr/bin/env python

import getpass
import sys
import telnetlib
import re
import pexpect
import base64

OST = str(sys.argv[1])
#user = raw_input("Enter your remote account: ")
#password = getpass.getpass()
user = "gss"
password = "pureethernet"

tn = telnetlib.Telnet(HOST)
tn.read_until("login: ")
tn.write(user + "\n")
if password:
    tn.read_until("Password: ")
    tn.write(password + "\n")
f = open("C:\\djangogirls\\blog\\templates\\startup-config.txt", "rb")
output.write(base64.b64decode(f))

**Comment by fi000** [comment]
frankherfert: Would you please help me when I have the same error with the following code:
 self.kmeans = load(open('data/kmeans_2.dat', 'r'))
